/**
 * This file is generated by `@better-auth/cli generate`.
 *
 * Run:
 *   bunx @better-auth/cli@latest generate --config ./scripts/better-auth.config.ts --output ./lib/schema/better-auth.ts --yes
 */

// Placeholder to keep TypeScript happy until the first generate is run.
export {};
